import type { Metadata } from "next";
import Dock from "@/components/Dock";
import { MouseProvider } from "@/components/MouseContext";
import Sidebar from "@/components/Sidebar";
import SmoothScroll from "@/components/SmoothScroll";
import ThreeBackground from "@/components/ThreeBackground";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <SmoothScroll>
          <MouseProvider>
            <ThreeBackground />
            <Sidebar />
            <Dock />
            <main className="perspective-[2500px]">{children}</main>
          </MouseProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}
