import type { Metadata } from "next";
import "./globals.css";
import ThreeBackground from "@/components/ThreeBackground";
import Sidebar from "@/components/Sidebar";
import Dock from "@/components/Dock";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ThreeBackground />
        <Sidebar />
        <Dock />
        <main>{children}</main>
      </body>
    </html>
  );
}
